# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'Day1107_test' do

pod 'AFNetworking'

pod 'MJRefresh'

pod 'MJExtension'

end

target 'Day1107_testTests' do

end

target 'Day1107_testUITests' do

end

